### ISSUE TITLE
missing materials/console/portal2_product_1.vtf

### ISSUE THREAD

**Issue by CatCoolYe** [p2sr/Portal2SpeedrunMod#34]
how to fix
![image](https://github.com/p2sr/Portal2SpeedrunMod/assets/69574827/48f653b7-3352-4270-a653-3357fdd7b9cc)

**Comment by Aruvelut-123** [comment]
I knew this! I recently get this error too!
And after a lot of searches, i found that because mod must be put in steam's installation folder and game can put in other drivers, so it will never search game file on other drives to pull out this message.
To fix this, modify mod's gameinfo.txt.
you will found a object called searchpaths, copy a new line of same format and then put your game path to there.
like this:
```
SearchPaths
		{
			Game				|gameinfo_path|.
			Game				"|gameinfo_path|../../common/Portal 2/portal2"
			Game				"Path_to_your_Portal_2_game_file/portal2"

		}
	}
```
Just simply replace Path_to_your_Portal_2_game_file to the path where you right click Portal 2 in steam and click 'Browser local file' to open's path for replace!

**Comment by CatCoolYe** [comment]
> I knew this! I recently get this error too! And after a lot of searches, i found that because mod must be put in steam's installation folder and game can put in other drivers, so it will never search game file on other drives to pull out this message. To fix this, modify mod's gameinfo.txt. you will found a object called searchpaths, copy a new line of same format and then put your game path to there. like this:
> 
> ```
> SearchPaths
> 		{
> 			Game				|gameinfo_path|.
> 			Game				"|gameinfo_path|../../common/Portal 2/portal2"
> 			Game				"Path_to_your_Portal_2_game_file/portal2"
> 
> 		}
> 	}
> ```
> 
> Just simply replace Path_to_your_Portal_2_game_file to the path where you right click Portal 2 in steam and click 'Browser local file' to open's path for replace!

Gonna test it. If it works. Thx

**Comment by CatCoolYe** [comment]
works. Thanks Aruvelut-123
